version: "3.8"

services:
  api:
    image: node:latest
    working_dir: /app
    ports:
      - "3301:3000"
    env_file:
      - ./api/.env
    # environment:
    #   - NEST_DEBUG=true
    volumes:
      - ./api:/app
    command: yarn start:dev
    depends_on:
      - redis
      - db
    links:
      - redis
      - db

  redis:
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "3401:6379"
    volumes:
      - type: bind
        source: data/redis
        target: /data
        bind:
          create_host_path: true

  db:
    image: mongo:latest
    restart: always
    command: mongod --replSet "rs0" --keyFile /data/keyfile --bind_ip_all
    ports:
      - "3402:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 10s
    volumes:
      - ./mongodb-keyfile:/data/keyfile
      - type: bind
        source: data/mongodb
        target: /data/db
        bind:
          create_host_path: true
